<?php

/**
 * Autoloads and registers class.
 *
 * @param string $class The fully-qualified class name.
 *
 * @return void
 */
spl_autoload_register(function ($class) {

    // Project-specific namespace prefix.
    $prefix = 'Drupal\\russiabank\\';
    // Base directory for the namespace prefix.
    $base_dir = __DIR__ . '/src/';
    // Check if the class uses the namespace prefix.
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // If no, move to the next registered autoloader.
        return;
    }
    // Get the relative class name.
    $relative_class = substr($class, $len);
    // Replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with '.php'.
    $file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';
    if (file_exists($file)) {
        // If the file exists, require it.
        require $file;
    }
});


function russiabank_menu()
{
    $page_callback_result = call_user_func_array($router_item['page_callback']);
    return [
        'bank' => [
            'title'               => 'BANK',
//            'page callback'       => 'Drupal\russiabank\Controller\MainController',
//            'access callback'     => 'user_access',
            'page callback' => 'hello_page',
            'access callback' => 'user_access',
            'access arguments' => array('access content'),
//            'page arguments'      => [Drupal\russiabank\Controller\MainController::class . '::contextAction'],
//            'access arguments'    => ['content'],
//            'type'                => MENU_CALLBACK
        ],
        'test' => [
            'title'               => 'TEST',
            'page callback'       => '\Drupal\\russiabank\\Controller\\MainController::contextAction',
            'access callback'  => TRUE,
        ]
    ];
}

function hello_page() {
    return array(
        '#type' => 'markup',
        '#markup' => t('Hello.'),
    );
}

function russiabank_page_callback()
{
    return array('#markup'=>'BANK INFO');
}