<?php

/**
 * Autoloads and registers class.
 *
 * @param string $class The fully-qualified class name.
 *
 * @return void
 */
spl_autoload_register(function ($class) {
    // Project-specific namespace prefix.
    $prefix = 'Drupal\\russiabank\\';
    // Base directory for the namespace prefix.
    $base_dir = __DIR__ . '/src/';
    // Check if the class uses the namespace prefix.
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // If no, move to the next registered autoloader.
        return;
    }
    // Get the relative class name.
    $relative_class = substr($class, $len);
    // Replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with '.php'.
    $file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';
    if (file_exists($file)) {
        // If the file exists, require it.
        require $file;
    }
});


function russiabank_menu()
{
    return [
        'bank' => [
            'title'               => 'BANK',
            'page callback'       => 'russiabank_page_callback',
            'page arguments'      => [Drupal\russiabank\Controller\MainController::class . '::contextAction'],
            'access arguments'    => ['content'],
            'type'                => MENU_CALLBACK
        ]
    ];
}

function russiabank_page_callback()
{
    return array('#markup'=>'BANK INFO');
}